### ISSUE TITLE
Incorporate 'dataType' in granule objects in the task output

### ISSUE THREAD

**Issue by jckoch** [podaac/cumulus-cnm-to-granule#4]
As part of investigating use of Cumulus throttled queues in context of CNM ingest workflows, we found that the 'QueueGranules' step (which handles the throttling) cannot handle the output given to it by 'TranslateMessage', the cnm-to-granule lambda.

'QueueGranules' requires a 'dataType' property to be present for each granule object.  If this lambda could incorporate that in its output, we could save having to create/integrate an intermediary lambda in the workflow.

Per Mark Boyd, the 'DiscoverGranules' Cumulus lambda - which can be used before 'QueueGranules' in a workflow - the 'dataType' value used is the collection name.  I'd think we'd want to follow that for the cnm-to-granule task also.

https://github.com/nasa/cumulus/blob/master/tasks/discover-granules/index.js#L180

**Comment by markdboyd** [comment]
Just to add on: queue-granules also expects a "version" property, which would be the collection version, so that would need to be added as well

**Comment by ngachung** [comment]
This issue has been fixed in: https://github.com/podaac/cumulus-cnm-to-granule/pull/12
Release: https://github.com/podaac/cumulus-cnm-to-granule/releases/tag/v1.4.0
