### ISSUE TITLE
Support https URI from cnm messages

### ISSUE THREAD

**Issue by mike-gangl** [podaac/cumulus-cnm-to-granule#79]
LP DAAC would like to build out the capability to reference https URIs from CNM messages. Currently the CNMtoGranule processes assumes an S3 url. 

Meno has supplied 2 example files, one CNM with https uris, and one which is the expected 'granule' output from the CNMToCumulus message processing. These should be used as test cases for the parsing function.

[cnmtogranule_https_input_sample.txt](https://github.com/podaac/cumulus-cnm-to-granule/files/7508573/cnmtogranule_https_input_sample.txt)

[cnmtogranule_https_output_sample.txt](https://github.com/podaac/cumulus-cnm-to-granule/files/7508571/cnmtogranule_https_output_sample.txt)

**Comment by ngachung** [comment]
This issue has been fixed in: https://github.com/podaac/cumulus-cnm-to-granule/pull/81
Release: https://github.com/podaac/cumulus-cnm-to-granule/releases/tag/v1.6.0
